routes/web.php
<?php

use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\DiaryController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\JournalController;
use App\Http\Controllers\JournalSubjectPageController;
use App\Http\Controllers\LessonController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\SchoolClassController;
use App\Http\Controllers\SetItemsPerPage;
use App\Http\Controllers\StudyYearController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherFeedbackController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'pages.home')->name('home');

Route::view('/history', 'pages.history');

Route::view('/contact_us', 'pages.contact_us');

Route::view('/not_available', 'pages.not_available');

Route::post('/items_per_age', SetItemsPerPage::class);

Route::post('/contact_us', [ContactUsController::class, 'send'])->name('contact-us');

Route::middleware('auth')->group(function () {
    Route::resource('users', UserController::class)->except(['create', 'edit']);

    Route::get('/users/create/{type}/{user?}', [UserController::class, 'create'])
        ->name('users.create')
        ->where('type', '^parent|student|employee$');

    Route::get('/users/{user}/edit/{type}', [UserController::class, 'edit'])
        ->name('users.edit')
        ->where('type', '^parent|student|employee$');
});

Route::middleware('auth')->group(function () {
    Route::resource('news', NewsController::class)->except(['index', 'show']);
});

Route::get('/news/sorted', [NewsController::class, 'indexSorted'])
    ->name('news.sorted');

Route::get('/news/search', [NewsController::class, 'search'])
    ->name('news.search');

Route::get('/news/category/{category}', [NewsController::class, 'getByCategoryName'])
    ->name('news.category-name')
    ->where(['category' => '^[АаБбВвГгҐґДдЕеЄєЖжЗзИиІіЇїЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЬьЮюЯя\'` -]+$']);

Route::resource('news', NewsController::class)->only(['index', 'show']);

Route::middleware('auth')->group(function () {
    Route::resource('events', EventController::class)->except(['index', 'show']);
});

Route::resource('events', EventController::class)->only(['index']);

Route::get('/events/sorted', [EventController::class, 'indexSorted'])
    ->name('events.sorted');

Route::get('/events/archive', [EventController::class, 'indexTrashed'])
    ->name('events.archive');

Route::get('/events/search', [EventController::class, 'search'])
    ->name('events.search');

Route::get('/events/category/{category}', [EventController::class, 'getByCategoryName'])
    ->name('events.category-name')
    ->where(['category' => '^[АаБбВвГгҐґДдЕеЄєЖжЗзИиІіЇїЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЬьЮюЯя\'` -]+$']);

Route::middleware('auth')->group(function () {
    Route::resource('subjects', SubjectController::class)->except(['index', 'show']);
});

Route::get('/subjects/class/{classNum?}', [SubjectController::class, 'index'])
    ->name('subjects.index');

Route::resource('subjects', SubjectController::class)->only(['show']);

Route::get('/employees', [EmployeeController::class, 'index'])
    ->name('employees.index');

Route::get('/employees/{employee}', [EmployeeController::class, 'show'])
    ->name('employees.show');

Route::middleware('auth')->group(function () {
    Route::resource('school-classes', SchoolClassController::class)->except(['index', 'show']);
});

Route::resource('school-classes', SchoolClassController::class)->only(['index', 'show']);

Route::middleware('auth')->group(function () {
    Route::get('/journals/show/{school_class}/{study_year}', [JournalController::class, 'show'])
        ->name('journals.show');
    Route::get('/journals/edit/{school_class}/{study_year}', [JournalController::class, 'edit'])
        ->name('journals.edit');
    Route::put('/journals/update/{school_class}/{study_year}', [JournalController::class, 'update'])
        ->name('journals.update');
    Route::delete('/journals/delete/{school_class}/{study_year}', [JournalController::class, 'destroy'])
        ->name('journals.destroy');
    Route::get('/journals/index-type/{type}', [JournalController::class, 'index'])
        ->name('journals.index')
        ->where('type', '^myJournals|allJournals$');
    Route::get('/journals/study-year/{study_year}/{is_journal_create}', [JournalController::class, 'getStudyYearClasses']);
    Route::resource('journals', JournalController::class)->only(['create', 'store']);

    Route::get('/journal-subject-pages/{journalSubjectPage}', [JournalSubjectPageController::class, 'show'])
        ->name('journal-subject-pages.show');
    Route::patch('/lessons/{lesson}', [LessonController::class, 'update'])
        ->name('lessons.update');
    Route::patch('/journal-cells', [LessonController::class, 'updateJournalCell'])
        ->name('journal-cells.update');
});

Route::middleware('auth')->group(function () {
    Route::resource('schedules', ScheduleController::class)->except(['index', 'show']);
});
Route::get('/schedules/{type}', [ScheduleController::class, 'index'])
    ->name('schedules.index')
    ->where('type', '^teachers|classes$');
Route::get('/schedules/{type}/{schedule}', [ScheduleController::class, 'show'])
    ->name('schedules.show')
    ->where('type', '^users|classes|usersOwn$');
Route::middleware('auth')->group(function () {
    Route::get('/diary/{studentId}/{weekNumber?}', [DiaryController::class, 'show'])
        ->name('diary.show');
    Route::post('/feedbacks}', [TeacherFeedbackController::class, 'store'])
        ->name('feedbacks.store');
    Route::get('study-years', [StudyYearController::class, 'create'])
        ->name('study-years.create');
    Route::post('study-years', [StudyYearController::class, 'store'])
        ->name('study-years.store');
});


require __DIR__ . '/auth.php';

resources/views/pages/news_management/create_news.blade.php
@extends('basic_layout')

@section('title', 'Створення новини')

@section('content')
    <div id="create-news-content" class="d-flex flex-row justify-content-center align-items-center">
        <div class="form w-full px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg m-4">
            <x-session-status class="mb-4" :status="session('status')"></x-session-status>
            <x-errors class="mb-4" :errors="$errors"></x-errors>
            <form method="POST" action="{{ route('news.store') }}">
                @csrf
                <div class="row">
                    <div class="col-xxl-3 col-xl-3 pb-2">
                        <x-label for="category" :value="__('Категорія')"></x-label>
                        <x-input list="categories" name="category" id="category" type="text" required max="255"
                                 class="input-field mt-1 w-full" :value="old('category')"></x-input>
                        <datalist id="categories">
                            @foreach($categories as $category)
                                <option value="{{ $category->name }}">
                            @endforeach
                        </datalist>
                    </div>
                    <div class="col-xxl-9 col-xl-9 pb-2">
                        <x-label for="title" :value="__('Назва')"></x-label>
                        <x-input id="title" class="input-field mt-1 w-full" type="text" name="title"
                                 :value="old('title')" required max="255"></x-input>
                    </div>
                </div>
                <div class="row">
                    <x-label for="description" class="pb-2">Опис новини:</x-label>
                    <textarea id="description" name="description" class="w-full input-field" rows="5">
                        {{ old('description') }}
                    </textarea>
                </div>
                <div class="row">
                    <x-label for="wyziwyg-editor" class="pb-2">Вміст новини:</x-label>
                    <textarea id="wyziwyg-editor" name="content">{{ old('content') }}</textarea>
                    <input id="wyziwyg-image" type="file" name="wyziwyg-image" class="d-none" onchange=""/>
                </div>
                <div class="flex items-center justify-center mt-3">
                    <x-submit-button class="sb-btn ml-3">Створити</x-submit-button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/news_management/news_catalogue.blade.php
@extends('basic_layout')

@section('title', 'Новини')

@include('news_management_layout.categories_sidebar', ['categories' => $categories])

@section('content')
    <x-errors class="mb-2 fs-5" :errors="$errors"></x-errors>
    @isset($isSearch)
        @isset($noResult)
            <div class="row my-2">
                <p class="text-center fs-3 col-12">Результати пошуку відсутні.</p>
            </div>
        @else
            <div class="row my-2">
                <p class="text-center fs-3 col-12">Результати пошуку:</p>
            </div>
        @endisset
    @endisset
    @isset($sortColumn)
        <div class="row my-2 justify-content-end">
            <form class="form col-xxl-10 col-lg-9 col-md-12 col-12 my-1"
                  method="GET" action="{{ route('news.search') }}" id="search">
                <div class="input-group">
                    <x-input name="searchParameter" type="search" placeholder="Пошук"
                             class="form-control input-field w-full border-end-0"></x-input>
                    <x-button class="btn input-group-append" type="submit">
                        <i class="bi bi-search fs-5"></i>
                    </x-button>
                </div>
            </form>
            <form class="col-xxl-2 col-lg-3 col-md-4 col-sm-6 col-8 my-1" method="GET"
                  action="{{ route('news.sorted') }}" id="sort-by-form">
                <x-select name="sortColumn" onchange="changeSortBy()" style="font-size: 18px;" class="w-full">
                    <option value="title" @selected($sortColumn == 'title')>Назва</option>
                    <option value="dateOld" @selected($sortColumn == 'dateOld')>Дата (спочатку старі)</option>
                    <option value="dateNew" @selected($sortColumn == 'dateNew')>Дата (спочатку нові)</option>
                    <option value="category" @selected($sortColumn == 'category')>Категорія</option>
                    <option value="author" @selected($sortColumn == 'author')>Автор</option>
                </x-select>
            </form>
        </div>
    @endisset
    @if(isset($news) && !$news->isEmpty())
        <div class="row">
            @foreach ($news as $singleNews)
                @include('news_management_layout.news_card', ['singleNews' => $singleNews])
            @endforeach
            {{ $news->onEachSide(2)->links() }}
        </div>
    @else
        <div class="row my-2">
            <p class="text-center fs-3 col-12">Опубліковані новини відсутні.</p>
        </div>
    @endif
@endsection

resources/views/pages/news_management/news_page.blade.php
@extends('basic_layout')

@section('title', $news->title)

@include('news_management_layout.categories_sidebar', ['categories' => $categories])

@section('content')
    <x-errors class="mb-2 fs-5" :errors="$errors"></x-errors>
    <b class="row w-full fs-2 d-flex justify-content-center text-center">{{ $news->title }}</b>
    <div class="post-meta w-full text-center">
        <span>
            <a href="{{ route('users.show', ['user' => $news->author->id]) }}">
                {{ $news->author->firstname . ' ' . $news->author->lastname }}
            </a>
        </span>
        <span class="mx-1">&bullet;</span>
        <span>
            <a href="{{ route('news.category-name', ['category' => $news->category->name]) }}">
                {{ $news->category->name }}
            </a>
        </span>
        <span class="mx-1">&bullet;</span>
        <span>{{ $news->created_at->translatedFormat('j F Y, G:i') }}</span>
        @if($news->updated_at != $news->created_at)
            <span class="mx-1">&bullet;</span>
            <span><i>Змінено: {{ $news->updated_at->translatedFormat('j F Y, G:i') }}</i></span>
        @endif
    </div>
    <div class="mb-2">
        {!! $news->content !!}
    </div>
@endsection

resources/views/pages/news_management/update_news.blade.php
@extends('basic_layout')

@section('title', 'Зміна новини')

@section('content')
    <div id="update-news-content" class="d-flex flex-row justify-content-center align-items-center">
        <div class="form w-full px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg m-4">
            <x-session-status class="mb-4" :status="session('status')"></x-session-status>
            <x-errors class="mb-4" :errors="$errors"></x-errors>
            <form method="POST" action="{{ route('news.update', ['news' => $news->id]) }}">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-xxl-3 col-xl-3 pb-2">
                        <x-label for="category" :value="__('Категорія')"></x-label>
                        <x-input list="categories" name="category" id="category" type="text" required max="255"
                                 class="input-field mt-1 w-full" :value="old('category', $news->category->name)">
                        </x-input>
                        <datalist id="categories">
                            @foreach($categories as $category)
                                <option value="{{ $category->name }}">
                            @endforeach
                        </datalist>
                    </div>
                    <div class="col-xxl-9 col-xl-9 pb-2">
                        <x-label for="title" :value="__('Назва')"></x-label>
                        <x-input id="title" class="input-field mt-1 w-full" type="text" name="title"
                                 :value="old('title', $news->title)" required max="255"></x-input>
                    </div>
                </div>
                <div class="row">
                    <x-label for="description" class="pb-2">Опис новини:</x-label>
                    <textarea id="description" name="description" class="w-full input-field" rows="5">
                        {{ old('description', $news->description) }}
                    </textarea>
                </div>
                <div class="row">
                    <x-label for="wyziwyg-editor" class="pb-2">Вміст новини:</x-label>
                    <textarea id="wyziwyg-editor" name="content">{{ old('content', $news->content) }}</textarea>
                    <input id="wyziwyg-image" type="file" name="wyziwyg-image" class="d-none" onchange=""/>
                </div>
                <div class="flex items-center justify-center mt-3">
                    <x-submit-button class="sb-btn ml-3">Змінити</x-submit-button>
                </div>
            </form>
        </div>
    </div>
@endsection