routes/web.php
<?php

use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\DiaryController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\JournalController;
use App\Http\Controllers\JournalSubjectPageController;
use App\Http\Controllers\LessonController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\SchoolClassController;
use App\Http\Controllers\SetItemsPerPage;
use App\Http\Controllers\StudyYearController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherFeedbackController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'pages.home')->name('home');

Route::view('/history', 'pages.history');

Route::view('/contact_us', 'pages.contact_us');

Route::view('/not_available', 'pages.not_available');

Route::post('/items_per_age', SetItemsPerPage::class);

Route::post('/contact_us', [ContactUsController::class, 'send'])->name('contact-us');

Route::middleware('auth')->group(function () {
    Route::resource('users', UserController::class)->except(['create', 'edit']);

    Route::get('/users/create/{type}/{user?}', [UserController::class, 'create'])
        ->name('users.create')
        ->where('type', '^parent|student|employee$');

    Route::get('/users/{user}/edit/{type}', [UserController::class, 'edit'])
        ->name('users.edit')
        ->where('type', '^parent|student|employee$');
});

Route::middleware('auth')->group(function () {
    Route::resource('news', NewsController::class)->except(['index', 'show']);
});

Route::get('/news/sorted', [NewsController::class, 'indexSorted'])
    ->name('news.sorted');

Route::get('/news/search', [NewsController::class, 'search'])
    ->name('news.search');

Route::get('/news/category/{category}', [NewsController::class, 'getByCategoryName'])
    ->name('news.category-name')
    ->where(['category' => '^[АаБбВвГгҐґДдЕеЄєЖжЗзИиІіЇїЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЬьЮюЯя\'` -]+$']);

Route::resource('news', NewsController::class)->only(['index', 'show']);

Route::middleware('auth')->group(function () {
    Route::resource('events', EventController::class)->except(['index', 'show']);
});

Route::resource('events', EventController::class)->only(['index']);

Route::get('/events/sorted', [EventController::class, 'indexSorted'])
    ->name('events.sorted');

Route::get('/events/archive', [EventController::class, 'indexTrashed'])
    ->name('events.archive');

Route::get('/events/search', [EventController::class, 'search'])
    ->name('events.search');

Route::get('/events/category/{category}', [EventController::class, 'getByCategoryName'])
    ->name('events.category-name')
    ->where(['category' => '^[АаБбВвГгҐґДдЕеЄєЖжЗзИиІіЇїЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЬьЮюЯя\'` -]+$']);

Route::middleware('auth')->group(function () {
    Route::resource('subjects', SubjectController::class)->except(['index', 'show']);
});

Route::get('/subjects/class/{classNum?}', [SubjectController::class, 'index'])
    ->name('subjects.index');

Route::resource('subjects', SubjectController::class)->only(['show']);

Route::get('/employees', [EmployeeController::class, 'index'])
    ->name('employees.index');

Route::get('/employees/{employee}', [EmployeeController::class, 'show'])
    ->name('employees.show');

Route::middleware('auth')->group(function () {
    Route::resource('school-classes', SchoolClassController::class)->except(['index', 'show']);
});

Route::resource('school-classes', SchoolClassController::class)->only(['index', 'show']);

Route::middleware('auth')->group(function () {
    Route::get('/journals/show/{school_class}/{study_year}', [JournalController::class, 'show'])
        ->name('journals.show');
    Route::get('/journals/edit/{school_class}/{study_year}', [JournalController::class, 'edit'])
        ->name('journals.edit');
    Route::put('/journals/update/{school_class}/{study_year}', [JournalController::class, 'update'])
        ->name('journals.update');
    Route::delete('/journals/delete/{school_class}/{study_year}', [JournalController::class, 'destroy'])
        ->name('journals.destroy');
    Route::get('/journals/index-type/{type}', [JournalController::class, 'index'])
        ->name('journals.index')
        ->where('type', '^myJournals|allJournals$');
    Route::get('/journals/study-year/{study_year}/{is_journal_create}', [JournalController::class, 'getStudyYearClasses']);
    Route::resource('journals', JournalController::class)->only(['create', 'store']);

    Route::get('/journal-subject-pages/{journalSubjectPage}', [JournalSubjectPageController::class, 'show'])
        ->name('journal-subject-pages.show');
    Route::patch('/lessons/{lesson}', [LessonController::class, 'update'])
        ->name('lessons.update');
    Route::patch('/journal-cells', [LessonController::class, 'updateJournalCell'])
        ->name('journal-cells.update');
});

Route::middleware('auth')->group(function () {
    Route::resource('schedules', ScheduleController::class)->except(['index', 'show']);
});
Route::get('/schedules/{type}', [ScheduleController::class, 'index'])
    ->name('schedules.index')
    ->where('type', '^teachers|classes$');
Route::get('/schedules/{type}/{schedule}', [ScheduleController::class, 'show'])
    ->name('schedules.show')
    ->where('type', '^users|classes|usersOwn$');
Route::middleware('auth')->group(function () {
    Route::get('/diary/{studentId}/{weekNumber?}', [DiaryController::class, 'show'])
        ->name('diary.show');
    Route::post('/feedbacks}', [TeacherFeedbackController::class, 'store'])
        ->name('feedbacks.store');
    Route::get('study-years', [StudyYearController::class, 'create'])
        ->name('study-years.create');
    Route::post('study-years', [StudyYearController::class, 'store'])
        ->name('study-years.store');
});


require __DIR__ . '/auth.php';

resources/views/pages/user_management/create_user.blade.php
@extends('basic_layout')

@section('title', 'Створення користувача')

@section('content')
    <div id="create-user-content" class="d-flex flex-row justify-content-center align-items-center">
        <div class="form w-full px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg m-4">
            <x-session-status class="mb-4" :status="session('status')"></x-session-status>
            <x-errors class="mb-4" :errors="$errors"></x-errors>
            <form method="POST" action="{{ route('users.store') }}" enctype="multipart/form-data">
                @csrf
                <input name="type" value="{{ $type }}" hidden>
                <div class="row">
                    @if($type == 'employee')
                        <div class="col-xxl-2 col-xl-3 col-lg-4 pb-2 text-center">
                            <x-label for="role" :value="__('Роль')"></x-label>
                            <x-select size="7" multiple name="roles[]" id="role" class="input-field overflow-auto"
                                      required>
                                @foreach($roles as $role)
                                    @if(in_array($role->name, old('roles', [])))
                                        <option value="{{ $role->name }}" selected>{{ $role->name }}</option>
                                    @else
                                        <option value="{{ $role->name }}">{{ $role->name}}</option>
                                    @endif
                                @endforeach
                            </x-select>
                        </div>
                        <div class="col-xxl-10 col-xl-9 col-lg-8 py-2 border text-center">
                            <div class="row">
                                @include('user_management_layout.common_create_form')
                            </div>
                        </div>
                    @else
                        <div class="py-2 border text-center">
                            <div class="row">
                                @include('user_management_layout.common_create_form')
                            </div>
                        </div>
                    @endif
                    @isset($studentId)
                        <input name="studentId" value="{{ $studentId }}" hidden>
                    @endisset
                </div>
                @if($type == 'employee')
                    <div class="row py-2 border mt-1">
                        @include('user_management_layout.create_employee_properties')
                    </div>
                @endif
                <div class="flex items-center justify-center mt-3">
                    <x-submit-button class="sb-btn ml-3">Створити</x-submit-button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/user_management/update_user.blade.php
@extends('basic_layout')

@section('title', 'Зміна даних користувача')

@section('content')
    <div id="create-user-content" class="d-flex flex-row justify-content-center align-items-center">
        <div class="form w-full px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg m-4">
            <x-session-status class="mb-4" :status="session('status')"></x-session-status>
            <x-errors class="mb-4" :errors="$errors"></x-errors>
            <form method="POST" action="{{ route('users.update', ['user' => $user->id]) }}" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row">
                    @if($type == 'employee')
                        <div class="col-xxl-2 col-xl-3 col-lg-4 pb-2 text-center">
                            <x-label for="roles" :value="__('Роль')"></x-label>
                            <x-select size="7" multiple name="roles[]" id="role" class="input-field overflow-auto"
                                      required>
                                @foreach($roles as $role)
                                    @if(in_array($role->name, old('roles', $user->getRoleNames()->toArray())))
                                        <option value="{{ $role->name }}" selected>{{ $role->name }}</option>
                                    @else
                                        <option value="{{ $role->name }}">{{ $role->name}}</option>
                                    @endif
                                @endforeach
                            </x-select>
                        </div>
                        <div class="col-xxl-10 col-xl-9 col-lg-8 py-2 border text-center">
                            <div class="row">
                                @include('user_management_layout.common_update_form', ['user' => $user])
                            </div>
                        </div>
                    @else
                        <div class="py-2 border text-center">
                            <div class="row">
                                @include('user_management_layout.common_update_form', ['user' => $user])
                            </div>
                        </div>
                    @endif

                </div>
                @if($type == 'employee')
                    <div class="row py-2 border mt-1">
                        @include('user_management_layout.update_employee_properties',
                            ['employeeProperties' => $user->employeeProperty])
                    </div>
                @endif
                <div class="flex items-center justify-center mt-3">
                    <x-submit-button class="sb-btn ml-3">Змінити дані</x-submit-button>
                    @if($type == 'student')
                        <a href="{{ route('users.create', ['type' => 'parent', 'user' => $user->id]) }}">
                            <x-button class="sb-btn ml-3">Додати батьків</x-button>
                        </a>
                    @endif
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/user_management/user_profile.blade.php
@extends('basic_layout')

@section('title', $user->firstname . ' ' . $user->lastname)

@section('content')
    <div class="user-profile row">
        <div class="col-lg-3 col-md-4 d-flex justify-content-center">
            <div class="user-photo-container">
                @if($user->photo_filepath != "")
                    <img src="@storageAsset($user->photo_filepath)" alt=""/>
                @else
                    <i class="bi bi-person fs-1"></i>
                @endif
            </div>
        </div>
        <div class="col-lg-9 col-md-8 text-break">
            <div class="section-header d-flex justify-content-between align-items-center mb-3">
                <h2>Особиста інформація</h2>
            </div>
            <div class="row">
                <div class="col-xxl-4 col-lg-6 border">
                    <p>Ім'я: {{ $user->firstname }}</p>
                    <p>Прізвище: {{ $user->lastname }}</p>
                    <p>По-батькові: {{ $user->patronymic }}</p>
                </div>
                <div class="col-xxl-4 col-lg-6 border">
                    @if($user->gender == 'male')
                        <p>Стать: чоловік</p>
                    @else
                        <p>Стать: жінка</p>
                    @endif
                    <p>Дата народження: {{ $user->birth_date }}</p>
                </div>
                <div class="col-xxl-4 border">
                    <p>Адреса: {{ $user->address }}</p>
                    <p>Телефон: {{ $user->phone ?? '-' }}</p>
                    <p>Пошта: {{ $user->email }}</p>
                </div>
            </div>
            @if($user->hasRole('student') && !$user->parents->isEmpty())
                <div class="section-header d-flex justify-content-between align-items-center mb-3">
                    <h2>Батьки</h2>
                </div>
                <div class="row">
                    @foreach($user->parents as $parent)
                        <div class="col-xxl-4 col-lg-6 border">
                            @if($parent->gender == 'male')
                                <p class="text-center fs-4"><strong>Батько</strong></p>
                            @else
                                <p class="text-center fs-4"><b>Матір</b></p>
                            @endif
                            <p>Ім'я: {{ $parent->firstname }}</p>
                            <p>Прізвище: {{ $parent->lastname }}</p>
                            <p>По-батькові: {{ $parent->patronymic }}</p>
                        </div>
                    @endforeach
                </div>
            @elseif($user->hasRole('parent') && !$user->children->isEmpty())
                <div class="section-header d-flex justify-content-between align-items-center mb-3">
                    <h2>Діти</h2>
                </div>
                <div class="row mb-2">
                    @foreach($user->children as $child)
                        <div class="col-xxl-4 col-lg-6 border">
                            <p>Ім'я: {{ $child->firstname }}</p>
                            <p>Прізвище: {{ $child->lastname }}</p>
                            <p>По-батькові: {{ $child->patronymic }}</p>
                        </div>
                    @endforeach
                </div>
            @elseif(!$user->hasAnyRole('parent', 'student') && $user->employeeProperty != null)
                <div class="section-header d-flex justify-content-between align-items-center mb-3">
                    <h2>Професійна інформація</h2>
                </div>
                <div class="row mb-2">
                    <div class="col-xl-4 border">
                        <p>Позиція: {{ $user->employeeProperty->position }}</p>
                        <p>Науковий ступінь: {{ $user->employeeProperty->science_degree }}</p>
                        <p>Досвід: {{ $user->employeeProperty->experience }}</p>
                    </div>
                    <div class="col-xl-8 border">
                        <p>Біографія:</p>
                        <p>{{ $user->employeeProperty->biography }}</p>
                    </div>
                </div>
            @endif
        </div>
    </div>
@endsection

resources/views/pages/user_management/users_catalogue.blade.php
@extends('basic_layout')

@section('title', 'Список користувачів')

@section('content')
    <x-errors class="mb-2 fs-5" :errors="$errors"></x-errors>
    <div class="overflow-auto my-1">
        <table class="user-list table table-striped table-bordered text-center m-0">
            <thead>
            <tr>
                <th scope="col">№</th>
                <th scope="col">Ім'я</th>
                <th scope="col">Прізвище</th>
                <th scope="col">По-батькові</th>
                <th scope="col">Стать</th>
                <th scope="col">Дата народження</th>
                <th scope="col">Адреса</th>
                <th scope="col">Телефон</th>
                <th scope="col">Пошта</th>
                <th scope="col">Ролі</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($users as $index => $user)
                <tr class="align-middle">
                    <th scope="row">{{ $index + 1  }}</th>
                    <td>{{ $user->firstname }}</td>
                    <td>{{ $user->lastname }}</td>
                    <td>{{ $user->patronymic }}</td>
                    @if($user->gender == 'male')
                        <td>Чоловік</td>
                    @else
                        <td>Жінка</td>
                    @endif
                    <td>{{ $user->birth_date }}</td>
                    <td>{{ $user->address }}</td>
                    <td>{{ $user->phone }}</td>
                    <td>{{ $user->email }}</td>
                    <td>
                        @foreach ($user->getRoleNames() as $role)
                            {{ $role . " " }}
                        @endforeach
                    </td>
                    <td>
                        @if($user->getRoleNames()->contains('parent'))
                            <a href="{{ route('users.edit', ['user' => $user->id, 'type' => 'parent']) }}"
                               class="btn btn-warning"><i class="bi bi-pencil-fill"></i></a>
                        @elseif($user->getRoleNames()->contains('student'))
                            <a href="{{ route('users.edit', ['user' => $user->id, 'type' => 'student']) }}"
                               class="btn btn-warning"><i class="bi bi-pencil-fill"></i></a>
                        @else
                            <a href="{{ route('users.edit', ['user' => $user->id, 'type' => 'employee']) }}"
                               class="btn btn-warning"><i class="bi bi-pencil-fill"></i></a>
                        @endif
                    </td>
                    <td>
                        <form method="POST" action="{{ route('users.destroy', ['user' => $user->id]) }}">
                            @csrf
                            @method('DELETE')
                            <span class="btn btn-danger"
                                  onclick="deletionSubmit('Ви впевнені, що хочете видалити даного користувача?',
                                    this.closest('form'))">
                                <i class="bi bi-trash"></i>
                            </span>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    {{ $users->onEachSide(2)->links() }}
@endsection