routes/web.php
<?php

use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\DiaryController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\JournalController;
use App\Http\Controllers\JournalSubjectPageController;
use App\Http\Controllers\LessonController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\SchoolClassController;
use App\Http\Controllers\SetItemsPerPage;
use App\Http\Controllers\StudyYearController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherFeedbackController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'pages.home')->name('home');

Route::view('/history', 'pages.history');

Route::view('/contact_us', 'pages.contact_us');

Route::view('/not_available', 'pages.not_available');

Route::post('/items_per_age', SetItemsPerPage::class);

Route::post('/contact_us', [ContactUsController::class, 'send'])->name('contact-us');

Route::middleware('auth')->group(function () {
    Route::resource('users', UserController::class)->except(['create', 'edit']);

    Route::get('/users/create/{type}/{user?}', [UserController::class, 'create'])
        ->name('users.create')
        ->where('type', '^parent|student|employee$');

    Route::get('/users/{user}/edit/{type}', [UserController::class, 'edit'])
        ->name('users.edit')
        ->where('type', '^parent|student|employee$');
});

Route::middleware('auth')->group(function () {
    Route::resource('news', NewsController::class)->except(['index', 'show']);
});

Route::get('/news/sorted', [NewsController::class, 'indexSorted'])
    ->name('news.sorted');

Route::get('/news/search', [NewsController::class, 'search'])
    ->name('news.search');

Route::get('/news/category/{category}', [NewsController::class, 'getByCategoryName'])
    ->name('news.category-name')
    ->where(['category' => '^[АаБбВвГгҐґДдЕеЄєЖжЗзИиІіЇїЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЬьЮюЯя\'` -]+$']);

Route::resource('news', NewsController::class)->only(['index', 'show']);

Route::middleware('auth')->group(function () {
    Route::resource('events', EventController::class)->except(['index', 'show']);
});

Route::resource('events', EventController::class)->only(['index']);

Route::get('/events/sorted', [EventController::class, 'indexSorted'])
    ->name('events.sorted');

Route::get('/events/archive', [EventController::class, 'indexTrashed'])
    ->name('events.archive');

Route::get('/events/search', [EventController::class, 'search'])
    ->name('events.search');

Route::get('/events/category/{category}', [EventController::class, 'getByCategoryName'])
    ->name('events.category-name')
    ->where(['category' => '^[АаБбВвГгҐґДдЕеЄєЖжЗзИиІіЇїЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЬьЮюЯя\'` -]+$']);

Route::middleware('auth')->group(function () {
    Route::resource('subjects', SubjectController::class)->except(['index', 'show']);
});

Route::get('/subjects/class/{classNum?}', [SubjectController::class, 'index'])
    ->name('subjects.index');

Route::resource('subjects', SubjectController::class)->only(['show']);

Route::get('/employees', [EmployeeController::class, 'index'])
    ->name('employees.index');

Route::get('/employees/{employee}', [EmployeeController::class, 'show'])
    ->name('employees.show');

Route::middleware('auth')->group(function () {
    Route::resource('school-classes', SchoolClassController::class)->except(['index', 'show']);
});

Route::resource('school-classes', SchoolClassController::class)->only(['index', 'show']);

Route::middleware('auth')->group(function () {
    Route::get('/journals/show/{school_class}/{study_year}', [JournalController::class, 'show'])
        ->name('journals.show');
    Route::get('/journals/edit/{school_class}/{study_year}', [JournalController::class, 'edit'])
        ->name('journals.edit');
    Route::put('/journals/update/{school_class}/{study_year}', [JournalController::class, 'update'])
        ->name('journals.update');
    Route::delete('/journals/delete/{school_class}/{study_year}', [JournalController::class, 'destroy'])
        ->name('journals.destroy');
    Route::get('/journals/index-type/{type}', [JournalController::class, 'index'])
        ->name('journals.index')
        ->where('type', '^myJournals|allJournals$');
    Route::get('/journals/study-year/{study_year}/{is_journal_create}', [JournalController::class, 'getStudyYearClasses']);
    Route::resource('journals', JournalController::class)->only(['create', 'store']);

    Route::get('/journal-subject-pages/{journalSubjectPage}', [JournalSubjectPageController::class, 'show'])
        ->name('journal-subject-pages.show');
    Route::patch('/lessons/{lesson}', [LessonController::class, 'update'])
        ->name('lessons.update');
    Route::patch('/journal-cells', [LessonController::class, 'updateJournalCell'])
        ->name('journal-cells.update');
});

Route::middleware('auth')->group(function () {
    Route::resource('schedules', ScheduleController::class)->except(['index', 'show']);
});
Route::get('/schedules/{type}', [ScheduleController::class, 'index'])
    ->name('schedules.index')
    ->where('type', '^teachers|classes$');
Route::get('/schedules/{type}/{schedule}', [ScheduleController::class, 'show'])
    ->name('schedules.show')
    ->where('type', '^users|classes|usersOwn$');
Route::middleware('auth')->group(function () {
    Route::get('/diary/{studentId}/{weekNumber?}', [DiaryController::class, 'show'])
        ->name('diary.show');
    Route::post('/feedbacks}', [TeacherFeedbackController::class, 'store'])
        ->name('feedbacks.store');
    Route::get('study-years', [StudyYearController::class, 'create'])
        ->name('study-years.create');
    Route::post('study-years', [StudyYearController::class, 'store'])
        ->name('study-years.store');
});


require __DIR__ . '/auth.php';

resources/views/pages/subject_management/create_subject.blade.php
@extends('basic_layout')

@section('title', 'Створення шкільного предмету')

@section('content')
    <div class="d-flex flex-row justify-content-center align-items-center">
        <div class="form w-full px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg m-4">
            <x-session-status class="mb-4" :status="session('status')"></x-session-status>
            <x-errors class="mb-4" :errors="$errors"></x-errors>
            <form method="POST" action="{{ route('subjects.store') }}">
                @csrf
                <div class="row text-center d-flex justify-content-center">
                    <div class="col-xl-3 col-lg-4 col-md-6 pb-2">
                        <x-label for="teacher" :value="__('Вчителі')"></x-label>
                        <x-select size="4" multiple name="teachers[]" id="teacher" class="input-field overflow-auto"
                                  required>
                            @foreach($teachers as $teacher)
                                @if(in_array($teacher->id, old('teachers', [])))
                                    <option class="text-wrap" value="{{ $teacher->id }}" selected>
                                        {{ $teacher->lastname . ' ' . $teacher->firstname . ' ' . $teacher->patronymic}}
                                    </option>
                                @else
                                    <option class="text-wrap" value="{{ $teacher->id }}">
                                        {{ $teacher->lastname . ' ' . $teacher->firstname . ' ' . $teacher->patronymic}}
                                    </option>
                                @endif
                            @endforeach
                        </x-select>
                    </div>
                    <div class="col-xl-9 col-lg-8 row d-flex justify-content-center">
                        <div class="col-md-6 pb-2">
                            <x-label for="schoolPrograms" :value="__('Шкільна програма')"></x-label>
                            <x-input list="schoolPrograms" name="schoolProgram" id="schoolProgram" type="text"
                                     required max="255" class="input-field mt-1 w-full"
                                     :value="old('schoolProgram')"></x-input>
                            <datalist id="schoolPrograms">
                                @foreach($schoolPrograms as $schoolProgram)
                                    <option value="{{ $schoolProgram->name }}">
                                @endforeach
                            </datalist>
                        </div>
                        <div class="col-md-6 pb-2">
                            <x-label for="title" :value="__('Назва')"></x-label>
                            <x-input id="title" class="input-field mt-1 w-full" type="text" name="title"
                                     :value="old('title')" required max="255"></x-input>
                        </div>
                        <div class="col-xl-5 col-md-6 pb-2">
                            <x-label for="yearStudyHours" :value="__('Кількість годин в рік')"></x-label>
                            <x-input id="yearStudyHours" class="input-field mt-1 w-full" type="number"
                                     name="yearStudyHours" :value="old('yearStudyHours')"
                                     required min="8.75" max="525" step="0.25"></x-input>
                        </div>
                        <div class="col-xl-5 col-md-6 pb-2">
                            <x-label for="weekStudyHours" :value="__('Кількість годин в тиждень')"></x-label>
                            <x-input id="weekStudyHours" class="input-field mt-1 w-full" type="number"
                                     name="weekStudyHours" :value="old('weekStudyHours')"
                                     required min="0.25" max="15" step="0.25"></x-input>
                        </div>
                        <div class="col-xl-2 col-md-4 pb-2">
                            <x-label for="class" :value="__('Клас')"></x-label>
                            <x-input id="class" class="input-field mt-1 w-full" type="number" name="classNum"
                                     :value="old('classNum')" required min="1" max="11"></x-input>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <x-label for="wyziwyg-editor" class="pb-2">Опис предмету:</x-label>
                    <textarea id="wyziwyg-editor" name="description">{{ old('description') }}</textarea>
                    <input id="wyziwyg-image" type="file" name="wyziwyg-image" class="d-none" onchange=""/>
                </div>
                <div class="flex items-center justify-center mt-3">
                    <x-submit-button class="sb-btn ml-3">Створити</x-submit-button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/subject_management/subject_page.blade.php
@extends('basic_layout')

@section('title', $subject->title)

@section('content')
    <x-errors class="mb-2 fs-5" :errors="$errors"></x-errors>
    <b class="row w-full fs-2 d-flex justify-content-center text-center">{{ $subject->title }}</b>
    <div class="row d-flex justify-content-center" id="subject-hours">
        <span class="col-lg-4 col-md-6 text-center">
            <b>Кількість годин в рік:</b>&nbsp;{{+$subject->year_studyhours}}
        </span>
        <span class="col-lg-4 col-md-6 text-center">
            <b>Кількість годин в тиждень:</b>&nbsp;{{+$subject->week_studyhours}}
        </span>
        <span class="col-lg-4 col-md-6 text-center">
            <b>Шкільна програма:</b>&nbsp;{{$subject->schoolProgram->name}}
        </span>
    </div>
    <div>
        {!! $subject->description !!}
    </div>
    <b class="row w-full fs-3 d-flex justify-content-center text-center">Вчителі, які викладають предмет</b>
    <div class="d-flex justify-content-center row mb-2">
        @foreach($subject->teachers as $teacher)
            @include('employee_management_layout.employee_card', ['employee' => $teacher])
        @endforeach
    </div>
    <div class="row d-flex justify-content-center my-2">
        @can('update subject')
            <a href="{{ route('subjects.edit', ['subject' => $subject->id]) }}"
               class="col-xxl-3 col-lg-4 col-md-5 col-6 p-0">
                <x-button class="w-full justify-content-center">Змінити дані предмету</x-button>
            </a>
        @endcan
        @can('delete subject')
            <form class="col-xxl-2 col-lg-3 col-md-4 col-6 text-end p-0"
                  method="POST" action="{{ route('subjects.destroy', ['subject' => $subject->id]) }}">
                @csrf
                @method('DELETE')
                <x-button
                    onclick="deletionSubmit('Ви впевнені, що хочете видалити даний предмет?', this.closest('form'))"
                    class="w-full justify-content-center">Видалити предмет</x-button>
            </form>
        @endcan
    </div>
@endsection

resources/views/pages/subject_management/subjects_catalogue.blade.php
@extends('basic_layout')

@section('title', 'Шкільні предмети')

@section('content')
    @if(isset($groupedSubjects) && !$groupedSubjects->isEmpty() && $сlassNum)
        @include('subject_management_layout.selection_form', ['selectedClassNum' => $сlassNum])
        <div class="row d-flex justify-content-center">
            @foreach ($groupedSubjects as $subjects)
                <div class="subjects-list col-xxl-3 col-lg-4 col-sm-5 sm:max-w-md px-6 py-4 bg-white shadow-md
                            overflow-hidden sm:rounded-lg">
                    <h2>{{$subjects[0]->schoolProgram->name}}</h2>
                    <ul>
                        @foreach ($subjects as $subject)
                            <li>
                                <a href="{{route('subjects.show', ['subject' => $subject->id])}}">{{$subject->title}}</a>
                            </li>
                        @endforeach
                    </ul>
                </div>
            @endforeach
        </div>
    @elseif($сlassNum)
        @include('subject_management_layout.selection_form', ['selectedClassNum' => $сlassNum])
        <div class="row my-2">
            <p class="text-center fs-3 col-12">Список шкільних предметів даного класу ще не опубліковано.</p>
        </div>
    @else
        @include('subject_management_layout.selection_form', ['selectedClassNum' => 0])
    @endif
@endsection

resources/views/pages/subject_management/update_subject.blade.php
@extends('basic_layout')

@section('title', 'Зміна шкільного предмету. ' . $subject->title)

@section('content')
    <div id="update-news-content" class="d-flex flex-row justify-content-center align-items-center">
        <div class="form w-full px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg m-4">
            <x-session-status class="mb-4" :status="session('status')"></x-session-status>
            <x-errors class="mb-4" :errors="$errors"></x-errors>
            <form method="POST" action="{{ route('subjects.update', ['subject' => $subject->id]) }}">
                @csrf
                @method('PUT')
                <div class="row text-center d-flex justify-content-center">
                    <div class="col-xl-3 col-lg-4 col-md-6 pb-2">
                        <x-label for="teacher" :value="__('Вчителі')"></x-label>
                        <x-select size="4" multiple name="teachers[]" id="teacher" class="input-field overflow-auto"
                                  required>
                            @foreach($teachers as $teacher)
                                @if(in_array($teacher->id, old('teachers', $subject->teachers()->pluck('teacher_id')->toArray())))
                                    <option class="text-wrap" value="{{ $teacher->id }}" selected>
                                        {{ $teacher->lastname . ' ' . $teacher->firstname . ' ' . $teacher->patronymic}}
                                    </option>
                                @else
                                    <option class="text-wrap" value="{{ $teacher->id }}">
                                        {{ $teacher->lastname . ' ' . $teacher->firstname . ' ' . $teacher->patronymic}}
                                    </option>
                                @endif
                            @endforeach
                        </x-select>
                    </div>
                    <div class="col-xl-9 col-lg-8 row d-flex justify-content-center">
                        <div class="col-md-6 pb-2">
                            <x-label for="schoolPrograms" :value="__('Шкільна програма')"></x-label>
                            <x-input list="schoolPrograms" name="schoolProgram" id="schoolProgram" type="text" required
                                     max="255" class="input-field mt-1 w-full"
                                     :value="old('schoolProgram', $subject->schoolProgram->name)"></x-input>
                            <datalist id="schoolPrograms">
                                @foreach($schoolPrograms as $schoolProgram)
                                    <option value="{{ $schoolProgram->name }}">
                                @endforeach
                            </datalist>
                        </div>
                        <div class="col-md-6 pb-2">
                            <x-label for="title" :value="__('Назва')"></x-label>
                            <x-input id="title" class="input-field mt-1 w-full" type="text" name="title"
                                     :value="old('title', $subject->title)" required max="255"></x-input>
                        </div>
                        <div class="col-xl-5 col-md-6 pb-2">
                            <x-label for="yearStudyHours" :value="__('Кількість годин в рік')"></x-label>
                            <x-input id="yearStudyHours" class="input-field mt-1 w-full" type="number"
                                     name="yearStudyHours" required min="8.75" max="525" step="0.25"
                                     :value="old('yearStudyHours', $subject->year_studyhours)"></x-input>
                        </div>
                        <div class="col-xl-5 col-md-6 pb-2">
                            <x-label for="weekStudyHours" :value="__('Кількість годин в тиждень')"></x-label>
                            <x-input id="weekStudyHours" class="input-field mt-1 w-full" type="number"
                                     name="weekStudyHours" required min="0.25" max="15" step="0.25"
                                     :value="old('weekStudyHours', $subject->week_studyhours)"></x-input>
                        </div>
                        <div class="col-xl-2 col-md-4 pb-2">
                            <x-label for="class" :value="__('Клас')"></x-label>
                            <x-input id="class" class="input-field mt-1 w-full" type="number" name="classNum"
                                     :value="old('classNum', $subject->class_number)" required min="1" max="11"></x-input>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <x-label for="wyziwyg-editor" class="pb-2">Опис предмету:</x-label>
                    <textarea id="wyziwyg-editor" name="description">
                        {{ old('description', $subject->description) }}
                    </textarea>
                    <input id="wyziwyg-image" type="file" name="wyziwyg-image" class="d-none" onchange=""/>
                </div>
                <div class="flex items-center justify-center mt-3">
                    <x-submit-button class="sb-btn ml-3">Змінити</x-submit-button>
                </div>
            </form>
        </div>
    </div>
@endsection